routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MeetingRoomController;
use App\Http\Controllers\MeetingRoomBookController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\UserRoleMenuController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['guest'])->group(function () {
    Route::controller(AuthController::class)->group(function () {
        Route::get('', 'login')->name('login');
        Route::post('login', 'authenticate')->name('authenticate');
    });
});
Route::middleware(['auth'])->group(function () {
    Route::controller(DashboardController::class)->group(function () {
        Route::get('dashboard', 'index')->name('dashboard');
    });
    Route::resource('menus', MenuController::class)->except('create', 'show');
    Route::resource('submenus', SubmenuController::class)->except('create', 'show');
    Route::resource('user-roles', UserRoleController::class)->except('create', 'show');
    Route::resource('user-roles.menus', UserRoleMenuController::class)->only('index', 'store', 'destroy');
    Route::controller(UserController::class)->group(function () {
        Route::get('profile', 'profile')->name('profile');
        Route::get('edit-profile', 'editProfile')->name('edit-profile');
        Route::put('update-profile', 'updateProfile')->name('update-profile');
        Route::get('change-password', 'changePassword')->name('change-password');
        Route::put('update-password', 'updatePassword')->name('update-password');
    });
    Route::resource('users', UserController::class)->except('create', 'show', 'edit');
    Route::get('meeting-rooms/{meeting_room}/json', [MeetingRoomController::class, 'listBooks'])->name('meeting-rooms.json');
    Route::resource('meeting-rooms', MeetingRoomController::class)->only('index', 'show');
    Route::resource('meeting-rooms.books', MeetingRoomBookController::class)->except('show', 'edit', 'destory');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');
});

app/Models/UserRole.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserRole extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];
    public $timestamps = false;

    /**
     * @return user
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'role_id');
    }
    
    /**
     * @return access_menus
     */
    public function access_menus()
    {
        return $this->hasMany(UserRoleMenu::class, 'role_id');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\MeetingRoom;
use App\Models\MeetingRoomBook;
use Illuminate\Contracts\View\View;

class DashboardController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        $title = 'Dashboard';
        $meetingRooms = MeetingRoom::all();
        foreach ($meetingRooms as $meetingRoom) {
            $meetingRoom->total_book = MeetingRoomBook::where('meeting_room_id', $meetingRoom->id)->get()->count();
        }
        return view('dashboard.index', compact('title', 'meetingRooms'));
    }
}

app/Http/Controllers/UserRoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRoleRequest;
use App\Models\UserRole;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class UserRoleController extends Controller
{
    /**
     * @param UserRole $userRole
     * @return View 
     */
    public function index(): View
    {
        $title = 'Akses Pengguna';
        $userRoles = UserRole::all();
        $userRole = new UserRole();
        return view('dashboard.user-roles.index', compact('title', 'userRoles', 'userRole'));
    }

    /**
     * @param UserRoleRequest $request
     * @return RedirectResponse
     */
    public function store(UserRoleRequest $request): RedirectResponse
    {
        UserRole::create($request->all());
        return back()->with('success', 'Berhasil menambahkan akses pengguna');
    }

    /**
     * @param UserRole $userRole
     * @return View
     */
    public function edit(UserRole $userRole): View
    {
        $title = 'Ubah Akses Pengguna';
        return view('dashboard.user-roles.edit', compact('title', 'userRole'));
    }

    /**
     * @param UserRole $userRole
     * @param UserRoleRequest $request
     * @return RedirectResponse
     */
    public function update(UserRole $userRole, UserRoleRequest $request): RedirectResponse
    {
        $userRole->update($request->all());
        return redirect()->route('user-roles.index')->with('success', 'Berhasil mengubah akses pengguna');
    }

    /**
     * @param UserRole $userRole
     * @return RedirectResponse
     */
    public function destroy(UserRole $userRole): RedirectResponse
    {
        $userRole->delete();
        return back()->with('success', 'Berhasil menghapus akses pengguna');
    }
}

app/View/Components/user-roles/form.php
<?php

namespace App\View\Components\user-roles;

use Illuminate\View\Component;

class form extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.user-roles.form');
    }
}

resources/views/dashboard/user-roles/edit.blade.php
@extends('layouts.dashboard')

@section('dashboard_content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ $title ?? '' }}</h1>
    <form action="{{ route('user-roles.update', $userRole->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-md-8">
                @include('components.user-roles.form')
            </div>
        </div>
    </form>
</div>
<!-- /.container-fluid -->

@endsection

resources/views/dashboard/user-roles/index.blade.php
@extends('layouts.dashboard')

@section('dashboard_content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ $title ?? '' }}</h1>
    <div class="row">
        <div class="col-lg-6">
            @include('components.alert')
            <a href="" class="btn btn-primary mb-3" data-toggle="modal" data-target="#newRoleModal"><i class="fas fa-user-plus"></i> Tambah Akses</a>
            <!-- DataTales -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead class="text-center">
                                <tr>
                                    <th scope="col" class="text-center">No</th>
                                    <th scope="col">Akses</th>
                                    <th scope="col">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (!empty($userRoles) && count($userRoles))
                                    @php
                                        $no = 0;
                                    @endphp
                                    @foreach ($userRoles as $ur)
                                        <tr>
                                            <th scope="row" class="text-center">{{ ++$no }}</th>
                                            <td>{{ $ur->name ?? null }}</td>
                                            <td class="text-center">
                                                <div class="btn-group" role="group" aria-label="Basic example">
                                                    <a href="{{ route('user-roles.menus.index', $ur->id) }}" class="btn btn-warning"><i class="fas fa-user-cog"></i></a>
                                                    <a href="{{ route('user-roles.edit', $ur->id) }}" class="btn btn-success mr-2"><i class="fas fa-edit"></i> Ubah</a>
                                                    <form action="{{ route('user-roles.destroy', $ur->id) }}" method="POST">
                                                        @method('DELETE')
                                                        @csrf
                                                        <button type="submit" class="btn btn-danger" onclick="return confirm('Hapus data?');"><i class="fas fa-trash-alt"></i> Hapus</a>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

<!-- Modal -->
<div class="modal fade" id="newRoleModal" tabindex="-1" role="dialog" aria-labelledby="newRoleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newRoleModalLabel">Tambah Akses Pengguna</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('user-roles.store') }}" method="POST">
                @csrf
                <div class="modal-body">
                    @include('components.user-roles.form')
                </div>
            </form>
        </div>
    </div>
</div>

@endsection