routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MeetingRoomController;
use App\Http\Controllers\MeetingRoomBookController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\UserRoleMenuController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['guest'])->group(function () {
    Route::controller(AuthController::class)->group(function () {
        Route::get('', 'login')->name('login');
        Route::post('login', 'authenticate')->name('authenticate');
    });
});
Route::middleware(['auth'])->group(function () {
    Route::controller(DashboardController::class)->group(function () {
        Route::get('dashboard', 'index')->name('dashboard');
    });
    Route::resource('menus', MenuController::class)->except('create', 'show');
    Route::resource('submenus', SubmenuController::class)->except('create', 'show');
    Route::resource('user-roles', UserRoleController::class)->except('create', 'show');
    Route::resource('user-roles.menus', UserRoleMenuController::class)->only('index', 'store', 'destroy');
    Route::controller(UserController::class)->group(function () {
        Route::get('profile', 'profile')->name('profile');
        Route::get('edit-profile', 'editProfile')->name('edit-profile');
        Route::put('update-profile', 'updateProfile')->name('update-profile');
        Route::get('change-password', 'changePassword')->name('change-password');
        Route::put('update-password', 'updatePassword')->name('update-password');
    });
    Route::resource('users', UserController::class)->except('create', 'show', 'edit');
    Route::get('meeting-rooms/{meeting_room}/json', [MeetingRoomController::class, 'listBooks'])->name('meeting-rooms.json');
    Route::resource('meeting-rooms', MeetingRoomController::class)->only('index', 'show');
    Route::resource('meeting-rooms.books', MeetingRoomBookController::class)->except('show', 'edit', 'destory');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');
});

app/Models/Submenu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Submenu extends Model
{
    use HasFactory;

    protected $fillable = [
        'menu_id',
        'name',
        'url',
        'icon',
        'is_active',
    ];
    public $timestamps = false;

    /**
     * @return menu
     */
    public function menu()
    {
        return $this->belongsTo(Menu::class, 'menu_id');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\MeetingRoom;
use App\Models\MeetingRoomBook;
use Illuminate\Contracts\View\View;

class DashboardController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        $title = 'Dashboard';
        $meetingRooms = MeetingRoom::all();
        foreach ($meetingRooms as $meetingRoom) {
            $meetingRoom->total_book = MeetingRoomBook::where('meeting_room_id', $meetingRoom->id)->get()->count();
        }
        return view('dashboard.index', compact('title', 'meetingRooms'));
    }
}

app/Http/Controllers/SubmenuController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SubmenuRequest;
use App\Models\Menu;
use App\Models\Submenu;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class SubmenuController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        $title = 'Pengaturan Submenu';
        $submenus = Submenu::all();
        $submenu = new Submenu();
        $menus = Menu::all();
        return view('dashboard.submenus.index', compact('title', 'submenus', 'submenu', 'menus'));
    }

    /**
     * @param SubmenuRequest $request
     * @return RedirectResponse
     */
    public function store(SubmenuRequest $request): RedirectResponse
    {
        Submenu::create($request->all());
        return back()->with('success', 'Berhasil menambahkan submenu');
    }

    /**
     * @param Submenu $sumenu
     * @return View
     */
    public function edit(Submenu $submenu): View
    {
        $title = 'Ubah Menu';
        $menus = Menu::all();
        return view('dashboard.submenus.edit', compact('title', 'submenu', 'menus'));
    }

    /**
     * @param Submenu $submenu
     * @param SubmenuRequest $request
     * @return RedirectResponse
     */
    public function update(Submenu $submenu, SubmenuRequest $request): RedirectResponse
    {
        $submenu->update($request->all());
        return redirect()->route('submenus.index')->with('success', 'Berhasil mengubah submenu');
    }

    /**
     * @param Submenu $submenu
     * @return RedirectResponse
     */
    public function destroy(Submenu $submenu): RedirectResponse
    {
        $submenu->delete();
        return back()->with('success', 'Berhasil menghapus submenu');
    }
}

app/View/Components/submenus/form.php
<?php

namespace App\View\Components\submenus;

use Illuminate\View\Component;

class form extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.submenus.form');
    }
}

resources/views/dashboard/submenus/edit.blade.php
@extends('layouts.dashboard')

@section('dashboard_content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ $title ?? '' }}</h1>
    <form action="{{ route('submenus.update', $submenu->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-md-8">
                @include('components.submenus.form')
            </div>
        </div>
    </form>
</div>
<!-- /.container-fluid -->

@endsection

resources/views/dashboard/submenus/index.blade.php
@extends('layouts.dashboard')

@section('dashboard_content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ $title ?? '' }}</h1>
    <div class="row">
        <div class="col-lg">
            @include('components.alert')
            <a href="" class="btn btn-primary mb-3" data-toggle="modal" data-target="#newSubMenuModal"><i class="fas fa-plus-circle"></i> Tambah Submenu</a>
            <!-- DataTales -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead class="text-center">
                                <tr>
                                    <th scope="col">No</th>
                                    <th scope="col">Nama Submenu</th>
                                    <th scope="col">Menu</th>
                                    <th scope="col">Url</th>
                                    <th scope="col">Icon</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (!empty($submenus) && count($submenus))
                                    @php
                                        $no = 0;
                                    @endphp
                                    @foreach ($submenus as $sm)
                                        <tr>
                                            <th scope="row" class="text-center">{{ ++$no }}</th>
                                            <td>{{ $sm->name ?? null }}</td>
                                            <td>{{ $sm->menu->name ?? null }}</td>
                                            <td>{{ $sm->url ?? null }}</td>
                                            <td>{{ $sm->icon ?? null }}</td>
                                            @if($sm->is_active == 0)
                                                <td class="text-center">Tidak Aktif</td>
                                            @elseif($sm->is_active == 1)
                                                <td class="text-center">Aktif</td>
                                            @endif
                                            <td class="text-center">
                                                <a href="{{ route('submenus.edit', $sm->id) }}" class="btn btn-success mr-2"><i class="fas fa-edit"></i> Ubah</a>
                                                <form action="{{ route('submenus.destroy', $sm->id) }}" method="POST">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Hapus data?');"><i class="fas fa-trash-alt"></i> Hapus</a>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

<!-- Modal -->
<div class="modal fade" id="newSubMenuModal" tabindex="-1" role="dialog" aria-labelledby="newSubMenuModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newSubMenuModalLabel">Tambah Submenu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('submenus.store') }}" method="POST">
                @csrf
                <div class="modal-body">
                    @include('components.submenus.form')
                </div>
            </form>
        </div>
    </div>
</div>

@endsection