routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MeetingRoomController;
use App\Http\Controllers\MeetingRoomBookController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\UserRoleMenuController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['guest'])->group(function () {
    Route::controller(AuthController::class)->group(function () {
        Route::get('', 'login')->name('login');
        Route::post('login', 'authenticate')->name('authenticate');
    });
});
Route::middleware(['auth'])->group(function () {
    Route::controller(DashboardController::class)->group(function () {
        Route::get('dashboard', 'index')->name('dashboard');
    });
    Route::resource('menus', MenuController::class)->except('create', 'show');
    Route::resource('submenus', SubmenuController::class)->except('create', 'show');
    Route::resource('user-roles', UserRoleController::class)->except('create', 'show');
    Route::resource('user-roles.menus', UserRoleMenuController::class)->only('index', 'store', 'destroy');
    Route::controller(UserController::class)->group(function () {
        Route::get('profile', 'profile')->name('profile');
        Route::get('edit-profile', 'editProfile')->name('edit-profile');
        Route::put('update-profile', 'updateProfile')->name('update-profile');
        Route::get('change-password', 'changePassword')->name('change-password');
        Route::put('update-password', 'updatePassword')->name('update-password');
    });
    Route::resource('users', UserController::class)->except('create', 'show', 'edit');
    Route::get('meeting-rooms/{meeting_room}/json', [MeetingRoomController::class, 'listBooks'])->name('meeting-rooms.json');
    Route::resource('meeting-rooms', MeetingRoomController::class)->only('index', 'show');
    Route::resource('meeting-rooms.books', MeetingRoomBookController::class)->except('show', 'edit', 'destory');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');
});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'name',
    ];
    public $timestamps = false;

    /**
     * @return access_menus
     */
    public function access_menus()
    {
        return $this->belongsTo(UserRoleMenu::class, 'menu_id');
    }
    
    /**
     * @return submenus
     */
    public function submenus()
    {
        return $this->hasMany(Submenu::class, 'menu_id');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\MeetingRoom;
use App\Models\MeetingRoomBook;
use Illuminate\Contracts\View\View;

class DashboardController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        $title = 'Dashboard';
        $meetingRooms = MeetingRoom::all();
        foreach ($meetingRooms as $meetingRoom) {
            $meetingRoom->total_book = MeetingRoomBook::where('meeting_room_id', $meetingRoom->id)->get()->count();
        }
        return view('dashboard.index', compact('title', 'meetingRooms'));
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\MenuRequest;
use App\Models\Menu;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class MenuController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        $title = 'Pengaturan Menu';
        $menus = Menu::all();
        $menu = new Menu();
        return view('dashboard.menus.index', compact('title', 'menus', 'menu'));
    }

    /**
     * @param MenuRequest $request
     * @return RedirectResponse
     */
    public function store(MenuRequest $request): RedirectResponse
    {
        Menu::create($request->all());
        return back()->with('success', 'Berhasil menambahkan menu');
    }

    /**
     * @param Menu $menu
     * @return View
     */
    public function edit(Menu $menu): View
    {
        $title = 'Ubah Menu';
        return view('dashboard.menus.edit', compact('title', 'menu'));
    }

    /**
     * @param Menu $menu
     * @param MenuRequest $request
     * @return RedirectResponse
     */
    public function update(Menu $menu, MenuRequest $request): RedirectResponse
    {
        $menu->update($request->all());
        return redirect()->route('menus.index')->with('success', 'Berhasil mengubah menu');
    }

    /**
     * @param Menu $menu
     * @return RedirectResponse
     */
    public function destroy(Menu $menu): RedirectResponse
    {
        $menu->delete();
        return back()->with('success', 'Berhasil menghapus menu');
    }
}

app/View/Components/menus/form.php
<?php

namespace App\View\Components\menus;

use Illuminate\View\Component;

class form extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.menus.form');
    }
}

resources/views/dashboard/menus/edit.blade.php
@extends('layouts.dashboard')

@section('dashboard_content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ $title ?? '' }}</h1>
    <form action="{{ route('menus.update', $menu->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-md-8">
                @include('components.menus.form')
            </div>
        </div>
    </form>
</div>
<!-- /.container-fluid -->

@endsection

resources/views/dashboard/menus/index.blade.php
@extends('layouts.dashboard')

@section('dashboard_content')

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ $title ?? '' }}</h1>
    <div class="row">
        <div class="col-lg-6">
            @include('components.alert')
            <a href="" class="btn btn-primary mb-3" data-toggle="modal" data-target="#newMenuModal"><i class="fas fa-plus-circle"></i> Tambah Menu</a>
            <!-- DataTales -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead class="text-center">
                                <tr>
                                    <th scope="col">No</th>
                                    <th scope="col">Menu</th>
                                    <th scope="col">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (!empty($menus) && count($menus))
                                    @php
                                        $no = 0;
                                    @endphp
                                    @foreach ($menus as $m)
                                        <tr>
                                            <th scope="row" class="text-center">{{ ++$no }}</th>
                                            <td>{{ $m->name ?? null }}</td>
                                            <td class="text-center">
                                                <div class="btn-group" role="group" aria-label="Basic example">
                                                    <a href="{{ route('menus.edit', $m->id) }}" class="btn btn-success mr-2"><i class="fas fa-edit"></i> Ubah</a>
                                                    <form action="{{ route('menus.destroy', $m->id) }}" method="POST">
                                                        @method('DELETE')
                                                        @csrf
                                                        <button type="submit" class="btn btn-danger" onclick="return confirm('Hapus data?');"><i class="fas fa-trash-alt"></i> Hapus</a>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

<!-- Modal -->
<div class="modal fade" id="newMenuModal" tabindex="-1" role="dialog" aria-labelledby="newMenuModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newMenuModalLabel">Tambah Menu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('menus.store') }}"  method="POST">
                @csrf
                <div class="modal-body">
                    @include('components.menus.form')
                </div>
            </form>
        </div>
    </div>
</div>

@endsection